### ISSUE TITLE
História de Usuário#1 - Página inicial

### ISSUE THREAD

**Issue by danieltorresBR** [danieltorresBR/lais-avasus#1]
Ator principal: ALUNO
Obrigatória? SIM

>> No meu acesso, desejo saber se estou autenticado na plataforma.

- [x] CA#01: Estando autenticado utilizando o sistema de autenticação do Django, deverão ser apresentadas as seguintes informações do aluno:

- Nome completo;
- Data de nascimento, com a idade;
- CPF;
- Cursos matriculados.

- [x] CA#02: Quando o aluno estiver autenticado, o sistema deverá exibir o botão para encerrar a sessão. 

- [ ] CA#03: Quando o aluno estiver autenticado, será permitido a matrícula nos cursos disponíveis na plataforma, de acordo com os critérios estabelecidos na História de Usuário #5.

- [x] CA#04: Caso não esteja autenticado, o aluno poderá escolher entre as seguintes opções:

- Botão “Entrar” para acessar a página de Login
- Botão “Cadastre-se” para ir até a página do autocadastro (História de Usuário #2)
