### ISSUE TITLE
História de Usuário#2 - Autocadastro

### ISSUE THREAD

**Issue by danieltorresBR** [danieltorresBR/lais-avasus#2]
Ator principal: ALUNO
Obrigatória? SIM

>> Após acessar a página inicial da aplicação, desejo realizar o meu autocadastro para acessar o Ambiente Virtual de Aprendizagem

- [x] CA#01: Ao realizar o autocadastro, o aluno deverá informar os seguintes dados:
      - Nome Completo;
      - CPF;
      - Data de Nascimento;
      - Senha;
      - Confirmação Senha;
      - Indicador de privacidade (As pessoas podem ver meu progresso) - Valores possíveis: Sim, Não.

- [ ] CA#02: O sistema deverá validar a data de nascimento informada pelo usuário

- [ ] CA#03: O sistema deve validar o CPF

- [ ] CA#04: O sistema não deve permitir mais de um usuário com o mesmo CPF

- [ ] CA#05: O sistema deverá exibir uma mensagem de confirmação ou negação indicando o sucesso ou não do cadastro
