### ISSUE TITLE
História de Usuário#3 - Página de login

### ISSUE THREAD

**Issue by danieltorresBR** [danieltorresBR/lais-avasus#3]
Ator principal: ALUNO
Obrigatória? SIM

>> Ao acessar a página de login, desejo informar o meu CPF e senha para autenticar e ter acesso ao sistema. Em seguida, após autenticado com sucesso, o sistema deverá redirecionar meu acesso para página inicial (História de Usuário#1):

- [x] CA#01: O formulário de login deve apresentar os campos:
      - CPF;
      - Senha.
     
- [ ] CA#02: O formulário deverá exibir mensagem de validação, caso o CPF ou senha sejam inválidos.

- [x] CA#03: Com a autenticação correta, o aluno deve ser redirecionado para a página inicial (#1).

- [x] CA#04: O sistema deve utilizar o sistema de autenticação do Django
